### ISSUE TITLE
建议 .funignore 里面不要加入 mod.ts 或者在教程中提一下这个文件

### ISSUE THREAD

**Issue by 2234839** [justjavac/deno_serverless_aliyun#4]
我尝试 bootstrap 里面是 `deno run -A --unstable mod.ts` 的时候他会报错找不到该文件。
我翻看了一下 fun  build 后的目录 
![图片](https://user-images.githubusercontent.com/28727933/85360545-fb35c080-b54b-11ea-81da-66dbbd25dff1.png)
里面也确实没有。
但 server.js 就在里面，我找了一段时间才发现  .funignore  中去掉了 mode.ts ...

**Comment by justjavac** [comment]
对，运行 `deno run -A --unstable server.js`。

因为 serverless 的每个函数都是隔离的，如果运行 .ts 文件，那么冷启性能会非常低。

**Comment by justjavac** [comment]
如果使用 mod.ts 作为启动入门，那么在构建时，还需要把缓存构建进去，启动的时候增加 `--cached-only` 参数
